name: university_project_mobile
description: front end mobile university project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  mongo_dart: ^0.7.4+1
  get_server: ^1.1.1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  flutter_downloader: ^1.7.4
  permission_handler: ^8.1.4+2
  path_provider: ^2.0.2
  json_annotation: ^4.0.1
  nb_utils: ^4.5.0
  google_fonts: ^2.2.0
  cloudinary_public: ^0.11.0
  cached_network_image: ^3.2.0
  cloudinary_sdk: ^4.0.1+9
  intl: ^0.17.0
  image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
     - family: Roboto
       fonts:
        - asset: fonts/Roboto-Regular.ttf
     - family: Parisienne
       fonts:
        - asset: fonts/Parisienne-Regular.ttf
     - family: Dancing
       fonts:
        - asset: fonts/DancingScript-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
